module it.polimi.ingsw {
    requires javafx.controls;
    requires javafx.fxml;
    requires com.fasterxml.jackson.databind;
    requires java.sql;
    requires jdk.incubator.vector;
    requires jdk.jshell;
    requires java.desktop;
    requires java.management.rmi;
    requires java.rmi;
    requires javafx.media;

    exports it.polimi.ingsw.Model.Cards;
    opens it.polimi.ingsw.Model.Cards to javafx.fxml, com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.Tiles;
    opens it.polimi.ingsw.Model.Tiles to javafx.fxml, com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.Player;
    opens it.polimi.ingsw.Model.Player to javafx.fxml, com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.Cards.Slavers;
    opens it.polimi.ingsw.Model.Cards.Slavers to javafx.fxml, com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.Cards.Pirates;
    opens it.polimi.ingsw.Model.Cards.Pirates to javafx.fxml, com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.Cards.Smugglers;
    opens it.polimi.ingsw.Model.Cards.Smugglers to javafx.fxml, com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.Cards.AbandonedShip;
    opens it.polimi.ingsw.Model.Cards.AbandonedShip to javafx.fxml, com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.Cards.Epidemic;
    opens it.polimi.ingsw.Model.Cards.Epidemic to javafx.fxml, com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.Cards.OpenSpace;
    opens it.polimi.ingsw.Model.Cards.OpenSpace to javafx.fxml, com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.Cards.CombatZone;
    opens it.polimi.ingsw.Model.Cards.CombatZone to javafx.fxml, com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.Cards.MeteorSwarm;
    opens it.polimi.ingsw.Model.Cards.MeteorSwarm to javafx.fxml, com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.Cards.Planets;
    opens it.polimi.ingsw.Model.Cards.Planets to javafx.fxml, com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.Cards.AbandonedStation to com.fasterxml.jackson.databind;
    opens it.polimi.ingsw.Model.Cards.AbandonedStation to com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Network.Client.RMI to java.rmi;
    opens it.polimi.ingsw.Network.Client.RMI to java.rmi;
    exports it.polimi.ingsw.Network.Server.RMI to java.rmi;
    opens it.polimi.ingsw.Network.Server.RMI to java.rmi;
    exports it.polimi.ingsw.View to com.fasterxml.jackson.databind;
    opens it.polimi.ingsw.View to com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.View.TUI to com.fasterxml.jackson.databind;
    opens it.polimi.ingsw.View.TUI to com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Model.GameControl to com.fasterxml.jackson.databind;
    opens it.polimi.ingsw.Model.GameControl to com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.View.GUI to javafx.graphics, javafx.fxml;
    opens it.polimi.ingsw.View.GUI to javafx.fxml;
    exports it.polimi.ingsw.Model.Cards.Stardust;
    opens it.polimi.ingsw.Model.Cards.Stardust to com.fasterxml.jackson.databind, javafx.fxml;
    exports it.polimi.ingsw.Model.Cards.Utils_Cards;
    opens it.polimi.ingsw.Model.Cards.Utils_Cards to com.fasterxml.jackson.databind, javafx.fxml;
    exports it.polimi.ingsw.Model.Boards;
    opens it.polimi.ingsw.Model.Boards to com.fasterxml.jackson.databind, javafx.fxml;
    exports it.polimi.ingsw.Model.Boards.Utils_Boards;
    opens it.polimi.ingsw.Model.Boards.Utils_Boards to com.fasterxml.jackson.databind, javafx.fxml;
    exports it.polimi.ingsw.Model.Tiles.Utils_Tiles;
    opens it.polimi.ingsw.Model.Tiles.Utils_Tiles to com.fasterxml.jackson.databind, javafx.fxml;
    exports it.polimi.ingsw.Utils;
    opens it.polimi.ingsw.Utils to com.fasterxml.jackson.databind, javafx.fxml;
    exports it.polimi.ingsw.Utils.RemoveTile;
    opens it.polimi.ingsw.Utils.RemoveTile to com.fasterxml.jackson.databind, javafx.fxml;
    exports it.polimi.ingsw.Utils.Dice to com.fasterxml.jackson.databind;
    opens it.polimi.ingsw.Utils.Dice to com.fasterxml.jackson.databind;
    exports it.polimi.ingsw.Utils.EventBus;
    opens it.polimi.ingsw.Utils.EventBus to com.fasterxml.jackson.databind, javafx.fxml;
    exports it.polimi.ingsw.Network.Client;
    opens it.polimi.ingsw.Network.Client to com.fasterxml.jackson.databind, javafx.fxml;
    exports it.polimi.ingsw.Network;
    opens it.polimi.ingsw.Network to com.fasterxml.jackson.databind, javafx.fxml;


}